name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'Containerfile' # Only trigger if Dockerfile changes
  workflow_dispatch: # Allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC - adjust as needed (e.g., '0 0 * * 0' for weekly)

env:
  IMAGE_NAME: caddy-cloudflare # Your repository name
  REGISTRY: ghcr.io
  GITHUB_USERNAME: TheMoltenJack # Your GitHub username

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max # Store build cache

      - name: Verify pushed image (optional)
        run: |
          echo "Successfully pushed images:"
          echo "${{ steps.meta.outputs.tags }}"
